export const listings = [
  {
    id: 1,
    title: "Refugio La Villa",
    location: "Sogamoso, Boyacá, Colombia",
    coordinates: [5.7147, -72.9331],
    price: "COP 232433/night",
    maxGuests: 6,
    rating: 4.9,
    category: "villa",
    featured: true,
    description: "🏡 Hermosa casa privada con zona verde y parqueadero, rodeada de cerca viva que brinda privacidad y una agradable sensación campestre. Ubicada a la entrada de Sogamoso a solo 5 minutos del centro y 10 minutos de Tibasosa o Nobsa. Espacio acogedor, ideal para descanso, viajes de trabajo o estudio. Sus ambientes luminosos y zona exterior ofrecen comodidad y tranquilidad después de una jornada laboral o un día de turismo. Perfecta para parejas y familias. Ubicada en condominio tranquilo y seguro.",
    amenities: [
      'Parqueadero privado al ingreso de la casa',
      'Internet de alta velocidad con fibra óptica',
      'Smart TV',
      'Cocina totalmente equipada',
      'Electrodomésticos menores listos para usar',
      'Sala y comedor amplios',
      'Excelente iluminación natural durante el día',
      'Conexión directa a zona exterior privada',
      '3 habitaciones amplias y bien iluminadas',
      'Cama doble en cada habitación',
      'Colchones ortopédicos',
      'Ropa de cama de alta calidad',
      'Clósets amplios',
      'Cortinas y persianas blackout',
      '2 baños completos',
      'Baño privado en habitación principal',
      'Calentador de agua a gas',
      'Zona verde privada ideal para desayunos al aire libre o un café en la tarde',
      'Ambiente tranquilo y seguro',
      'Condominio con seguridad 24/7',
      'Senderos peatonales para caminar o pasear con tu mascota',
      'Zona comercial cercana: tiendas, restaurantes, cafeterías, gimnasio, pilates, peluquería, salón de belleza',
      'Se permiten mascotas',
      'Apto para fumadores',
      'Llegada autónoma con cerradura de teclado',
      'Patio trasero privado',
      'Mobiliario exterior',
      'Zona de comida al aire libre',
      'Tumbonas',
      'Estacionamiento gratuito en las instalaciones y en la calle',
      'Gimnasio compartido cerca',
      'Cámaras de seguridad en la parte exterior',
      'Wifi',
      'Refrigerador',
      'Utensilios básicos para cocinar',
      'Ollas y sartenes, aceite, sal y pimienta',
      'Platos y cubiertos',
      'Estufa de gas de acero inoxidable',
      'Horno doble de acero inoxidable',
      'Cafetera de filtro',
      'Copas de vino',
      'Licuadora',
      'Mesa del comedor',
      'Productos de limpieza',
      'Jabón corporal',
      'Agua caliente',
      'Gel de ducha',
      'Ganchos para la ropa',
      'Sábanas de algodón',
      'Plancha',
      'Tendedero de ropa',
      'TV',
      'Entrada independiente',
      'Entrada por otra calle o edificio',
      'No disponible: Lavadora',
      'No disponible: Secadora',
      'No disponible: Aire acondicionado',
      'No disponible: Servicios básicos',
      'No disponible: Detector de humo',
      'No disponible: Detector de monóxido de carbono',
      'No disponible: Calefacción',
    ],
    image: "https://images.unsplash.com/photo-1505691938895-1758d7feb511"
  },
  {
    id: 2,
    title: "Duplex La Villa -Sogamoso Centro",
    location: "Sogamoso, Boyacá, Colombia",
    coordinates: [5.7147, -72.9331],
    price: "COP 169360/night",
    maxGuests: 5,
    rating: 4.9,
    category: "duplex",
    featured: true,
    description: "Acerca de este espacio\nDúplex moderno de 80 m² en el centro de Sogamoso, cerca de la Plaza de la Villa y la Plaza 6 de Septiembre. Totalmente equipado, combina diseño contemporáneo y esencia local. Ubicado en el corazón de la ciudad, es un lugar muy tranquilo, ideal para descansar o trabajar. Cuenta con cocina equipada, luz natural y todos los servicios para una estadía cómoda.\nPerfecto para explorar la ciudad caminando, disfrutar su historia y relajarte en un espacio amplio y acogedor.\n\nEl espacio\nCuenta con estacionamiento privado y en su interior espacios amplios y luminosos, cocina equipada, Wi-Fi, Smart TV y todas las comodidades necesarias para una estadía placentera, ya sea de trabajo o descanso. Sus tres habitaciones bien distribuidas ofrecen descanso ideal para familias, parejas o grupos pequeños.\n\nAcceso de los huéspedes\nEstacionamiento privado",
    amenities: [
      'Baño',
      'Productos de limpieza',
      'Champú',
      'Agua caliente',
      'Gel de ducha',
      'Dormitorio y lavadero',
      'Servicios básicos',
      'Toallas, sábanas, jabón y papel higiénico',
      'Ganchos para la ropa',
      'Persianas o cortinas opacas',
      'Tendedero de ropa',
      'Espacio para guardar ropa: armario',
      'Entretenimiento',
      'TV',
      'Familia',
      'Seguros para ventanas',
      'Seguridad en el hogar',
      'Cámaras de seguridad en la parte exterior de la propiedad',
      'El edificio cuenta con CCTV en todas las zonas comunas, ingreso y hall de entrada.',
      'Extintor de incendios',
      'Botiquín de primeros auxilios',
      'Internet y oficina',
      'Wifi',
      'Utensilios y vajilla',
      'Cocina',
      'Los huéspedes pueden cocinar en este espacio',
      'Refrigerador',
      'Utensilios básicos para cocinar',
      'Ollas y sartenes, aceite, sal y pimienta',
      'Platos y cubiertos',
      'Bols, palitos chinos, platos, tazas, etc.',
      'Congelador',
      'Estufa de gas de acero inoxidable',
      'Horno de acero inoxidable',
      'Cafetera: Máquina de café expreso',
      'Licuadora',
      'Mesa del comedor',
      'Café',
      'Características de la ubicación',
      'Lavandería cercana',
      'Estacionamiento e instalaciones',
      'Estacionamiento gratis en las instalaciones: 1 puesto',
      'Estacionamiento de pago en las instalaciones',
      'Servicios',
      'Se permiten mascotas',
      'No hay restricciones respecto los animales de asistencia',
      'Servicio de limpieza disponible: 2 horas al día, 3 días a la semana, costo: disponible por un costo adicional',
      'El anfitrión te va a recibir',
      'No incluidos',
      'No disponible: Lavadora',
      'No disponible: Secadora',
      'No disponible: Aire acondicionado',
      'No disponible: Detector de humo',
      'No disponible: Detector de monóxido de carbono',
      'No disponible: Calefacción',
    ],
    image: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688"
  }
];